# Generated by Django 2.2.6 on 2019-10-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191003_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageforlife',
            new_name='image',
        ),
    ]
